name: autogen-env
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pip:
    - requests
    - scikit-learn
    - jupyter
    - pyautogen